#!/usr/bin/python
 
from Tkinter import *
from math import *
import Pmw,string,os

root = Tk()
canvas = Pmw.ScrolledCanvas(root,canvas_background="white")
height = 512

lines = open(sys.argv[1])
while 1:
    line = lines.readline()
    if not line: break
    if line[0]=="_": continue
    if line[0]=="#": continue
    if line=="\n": continue
    line = line[:-1]
    (x,y,a) = map(string.atof,string.split(line))[:3]
    (x0,y0,x1,y1) = (x-2,y-2,x+2,y+2)
    if 0:
	canvas.create_rectangle(x0,y0,x1,y1,width=1,fill='black')
    else:
	c = 5*cos(a)
	s = 5*sin(a)
	canvas.create_line(x,y,x+c,y+s)
lines.close()

canvas.pack(expand=Y,fill=BOTH)
canvas.resizescrollregion()

root.mainloop()
